// Shared components
export { SuggestedFriends } from "./SuggestedFriends";
export type { SuggestedFriend } from "./SuggestedFriends";
export { SidebarFooter } from "./SidebarFooter";
export { SidebarProfileCard } from "./SidebarProfileCard";
export { NotificationItem } from "./NotificationItem";
export { NotificationList } from "./NotificationList";
export type { NotificationData } from "./NotificationList";
export { ProfileHeader } from "./ProfileHeader";
export type { ProfileStat, ProfileTab } from "./ProfileHeader";
export { SettingsLayout } from "./SettingsLayout";
export type { SettingsMenuItem } from "./SettingsLayout";
export { GeneralSettingsForm } from "./GeneralSettingsForm";
export { AccountSettings } from "./AccountSettings";
export { ThemeSettings } from "./ThemeSettings";
export { MobileDock } from "./MobileDock";
export { AppHeaderNav } from "./AppHeaderNav";
export { AppLeftSidebar } from "./AppLeftSidebar";
export { AppRightSidebar } from "./AppRightSidebar";
export { MainLayout } from "./MainLayout";
export { UserResultCard } from "./UserResultCard";
export { SuggestedFriendsFacebookCard } from "./SuggestedFriendsFacebookCard";
export { AppLogo } from "./AppLogo";
